[package]
name = "apidoc-gen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "apidoc-gen"
path = "src/main.rs"

[dependencies]
device-attestation = { path = "../device-attestation" }
username-indexer = { path = "../username-indexer" }
invite-tickets = { path = "../invite-tickets" }
turn = { path = "../turn" }
notifications = { path = "../notifications" }
utoipa.workspace = true
serde_json = { version = "1", features = ["preserve_order"] }
anyhow.workspace = true

[lints]
workspace = true
