[package]
name = "chain-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
chain-types.workspace = true
subxt = { workspace = true, features = ["jsonrpsee"] }
subxt-rpcs.workspace = true
subxt-signer = { workspace = true, features = ["subxt"] }
schnorrkel = "0.11"

anyhow.workspace = true
hex = "0.4"
thiserror.workspace = true

[dev-dependencies]
jsonrpsee-core = { version = "0.24", features = ["server"] }
jsonrpsee-server = "0.24"
tokio.workspace = true

[lints]
workspace = true
